import datetime

def create_stakeholder_report(agent_state: dict) -> str:
    """
    Takes the output from the LangGraph agent and formats it into a Markdown report.
    """
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    signal = agent_state.get("trading_signal", "UNKNOWN")
    reasoning = agent_state.get("reasoning", "No reasoning provided.")
    forecast = agent_state.get("forecast_data", "No forecast data available.")
    
    report = f"""# Energy Market Trading Report
**Generated:** {timestamp}

## 📊 Trading Signal
**Recommendation:** `{signal}`

## 🧠 Agent Reasoning
{reasoning}

## 📈 Forecast Summary
{forecast}

---
*This report was automatically generated by the Energy Trading Agent.*
"""
    return report
